### ISSUE TITLE
Download links in client changelog are gone

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/owncloud.org#1349]
Where are all the download links for the different client versions in https://owncloud.org/changelog/desktop-client ??? 

I guess this would be because the website is being fed by the changelog living on the client repo. **which does not contain the download links**. This is important since we point at the changelog quite often for people to test with previous versions/betas/release candidates. 

Also, because of this - version 2.4 has not yet been released (we're in rc2 right now), it appears with the release date `2017-12-XX` 😕 

Can we get the old links while we work in a more automatic solution - i.e. using GitHub's API together with using [GitHub Releases](https://help.github.com/articles/creating-releases/)

**Comment by michaelstingl** [comment]
We now have changelogs for all platforms in the GH repos:

- https://github.com/owncloud/client/blob/master/ChangeLog
- https://github.com/owncloud/core/blob/stable10/CHANGELOG.md
- https://github.com/owncloud/android/blob/master/CHANGELOG.md
- https://github.com/owncloud/ios/blob/master/Changelog.md

Changlogs now get imported automatically to owncloud.org.

Previously _someone(tm)_ copy-pasted changelogs (manually), added release notes (manually) and added download links (manually):
- https://github.com/owncloud/owncloud.org/blob/master/page-changelog.php
- https://github.com/owncloud/owncloud.org/blob/master/page-desktop.php

Is the changelog the right place for release notes?

For oC server, release notes are part of the docs:
https://doc.owncloud.org/server/latest/admin_manual/release_notes.html

Why not do the clients the same way?

What's the benefit of having download links in the changelog? I guess easily accessing old versions? Have a download page for older versions like other projects have it? (easy to implement as a quick fix)

We could discuss a process where we (automatically!) add download links to the changelog, but this hasn't been implemented yet…

**Comment by michaelstingl** [comment]
And yes, I'd love to have something like the [old strings.php](https://github.com/owncloud/owncloud.org/blob/master/strings.php) which feds some of the information on the owncloud.org website. Need to discuss what's available… JSON file on GH? Using the WP API? etc

**Comment by hurradieweltgehtunter** [comment]
download links for older versions have their own page now: https://owncloud.org/download/older-versions/
About the changelogs: We should sit together and set up a unified process.

**Comment by SamuAlfageme** [comment]
@hurradieweltgehtunter Thanks a bunch! 

>  About the changelogs: We should sit together and set up a unified process.

Agreed - anytime!

**Comment by michaelstingl** [comment]
@hurradieweltgehtunter please add some semantics:

- <section> for server, section for client (optional)
- id/name attribute for server/client section to link directly to the clients

**Comment by guruz** [comment]
https://owncloud.org/changelog/desktop-client does not have links to the issues either.
You can use the script I had in https://github.com/owncloud/administration-internal/blob/master/clients/desktop/make_html_changelog.php to convert the text-Changelog in the client github repo to HTML.

>  Need to discuss what's available… JSON file on GH? Using the WP API? etc

Why would you convert something to JSON first?

Just do what worked since forever and is now broken.

**Comment by jnweiger** [comment]
We should place the output of make_html_changes.php in github so that wordpress can pull it from there.
Currently it seems to pull the input to make_html_changes.php only.

It never appeared to me, why we should post a differnet changelog on github than what we link on the websites. That was wrong in the past, imho.

**Comment by guruz** [comment]
> We should place the output of make_html_changes.php in github so that wordpress can pull it from there.

That's exactly what page-desktop.php used to be.

> It never appeared to me, why we should post a differnet changelog on github than what we link on the websites. That was wrong in the past, imho.

Because the one in github doesn't have the link to .exe, .pkg etc under it.
Also the links are not clickable ;-)

**Comment by guruz** [comment]
As discussed with @jnweiger here the HTML to pull into https://owncloud.org/changelog/desktop-client/: https://github.com/owncloud/client/pull/6260

**Comment by guruz** [comment]
OK, now instead as suggest by @SamuAlfageme and discussed with @michaelstingl we're using the github release concept (based on git tags).
Therefore please check https://github.com/owncloud/owncloud.org/issues/1354#issuecomment-353940522 because right now https://owncloud.org/changelog/desktop-client  is totally broken :-/

**Comment by mmattel** [comment]
Broken for **all** changelog entries.

Visitor currently see eg ``[load-github id=”changelog-server” url=”https://raw.githubusercontent.com/owncloud/core/stable10/CHANGELOG.md”]``

Quick fix needed 🆘

**Comment by jnweiger** [comment]
@mmattel For a quick fix, see the links at the bottom of https://owncloud.org/changelog/desktop-client
@hurradieweltgehtunter please check what is wrong with the github importer.

**Comment by mmattel** [comment]
@jnweiger Thanks for the note, but a quick fix to look at the link given is not the solution.
The all changelog pages are public and are broken. This needs a quick fix...

**Comment by tomneedham** [comment]
> This needs a quick fix...

Agreed - this is a big regression on functionality at the moment and there is no nice workaround

**Comment by felixboehm** [comment]
@hurradieweltgehtunter

**Comment by hurradieweltgehtunter** [comment]
Fixed.

**Comment by michaelstingl** [comment]
👍

**Comment by hurradieweltgehtunter** [comment]
afaik all current changelogs are included via github changelog md's right?
There is a seperate page for older version downloads (https://owncloud.org/download/older-versions/). Would you still include dl links in changelogs? 
Anyway, you can do this by including them into the changelog files.
Is there anything left to be done or can this issue be closed?

**Comment by michaelstingl** [comment]
close for now

**Comment by guruz** [comment]
Still broken :-/

* https://owncloud.org/changelog/desktop-client/ does not have clickable links as it had before. I thought we link to https://github.com/owncloud/client/releases instead which has clickable links?
* People on central are confused about it too: https://central.owncloud.org/t/changelog-not-up-to-date/11651

> There is a seperate page for older version downloads (https://owncloud.org/download/older-versions/). 

Where is that linked from? IMHO it should be linked from owncloud.org/install and from owncloud.org/changelog/desktop-client.. :)

**Comment by hurradieweltgehtunter** [comment]
The changelog is taken from https://raw.githubusercontent.com/owncloud/client/master/ChangeLog automatically and markdown is parsed. If markdown links are included in this file, they will appear on the page. We don't do anything manually on oc.org side.
I included the link in the changelog page. On /download (formerly /install) it's already included.

**Comment by michaelstingl** [comment]
@hurradieweltgehtunter thanks for the explanation

@guruz @SamuAlfageme @jnweiger Please let us review the client release process to check how we can integrate here…

**Comment by hurradieweltgehtunter** [comment]
Maybe talk to @PVince81  He's doing it the same way for the server changelog

**Comment by guruz** [comment]
@michaelstingl @jnweiger this is **still** not fixed.
https://owncloud.org/changelog/desktop-client/ still does not contain links to the downloads. What's so hard about linking to /install and https://github.com/owncloud/client/releases/tag/v2.4.0 ? 

If you give me access to the website I'd rather do it myself than to beg here since 2 months. 

> and markdown is parsed

No need to have markdown, the links are automatically generated in https://github.com/owncloud/client/releases/tag/v2.4.0

**Comment by michaelstingl** [comment]
@guruz Yes, I'm totally aware of it. I need a quick meeting with you before any action is going on here.

**Comment by guruz** [comment]
@michaelstingl I'm already happy if you add a link "Clickable ChangeLog issues and download links on  https://github.com/owncloud/client/releases" :-)

**Comment by guruz** [comment]
...and one for "Current version downloads" to /install .. it really doesn't need to be perfect, just getting the old functionality back.
btw, which process updates https://owncloud.org/download/older-versions/ ?

**Comment by jnweiger** [comment]
https://owncloud.org/download/older-versions/ is a simple wordpress page. It was Last edited by Jürgen Weigert on December 28, 2017 at 11:25 am

I guess the process is to ping the web team for updates. :-)

**Comment by guruz** [comment]
@jnweiger Then we might as well have the older version links on https://github.com/owncloud/client/releases ?

**Comment by guruz** [comment]
Still not working. Good that a link to GitHub (nearly) fulfills the requirements..
https://central.owncloud.org/t/desktop-client-2-4-1-rc1-released/12072

**Comment by hurradieweltgehtunter** [comment]
> Still not working. Good that a link to GitHub (nearly) fulfills the requirements..
The links are still not in the changelog file

**Comment by guruz** [comment]
https://github.com/owncloud/owncloud.org/issues/1349#issuecomment-364175010 was just done by @jnweiger ... thx

> And is there a reason you link to github as download source and not oc.org/download?

Because it shows a nice Changelog with clickable issue links... this is what especially people that use rc's like to see.
(plus I don't have access to the oc.org wordpress)

**Comment by hurradieweltgehtunter** [comment]
This "solution" is only temporarily and has to be removed because it confuses the visitor and breaks the user experience. 
So far I still got no reason why you don't use markdown in the desktop changelog like in the tarball, ios and android changelogs. The process has changed since the relaunch so please adapt. It's nearly 3 months and the desktop changelogs are still not consistent with the others.

If we want to use github release pages and changelogs we need to discuss it and use it consistently on tarball etc. as well. But for now, markdown is the way to go.
